<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="6" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-02-13T10:01:36 IST" name="Suite" finished-at="2023-02-13T10:02:04 IST" duration-ms="28384">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidations.loginerrorValidation()[pri:0, instance:swethapanchumarthy.Tests.ErrorValidations@6fb365ed]" name="loginerrorValidation" class="swethapanchumarthy.Tests.ErrorValidations"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="SubmitOrderTest.submitOrder(java.util.HashMap)[pri:0, instance:swethapanchumarthy.Tests.SubmitOrderTest@7749bf93]" name="submitOrder" class="swethapanchumarthy.Tests.SubmitOrderTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2023-02-13T10:01:36 IST" name="Submit Order Test" finished-at="2023-02-13T10:02:03 IST" duration-ms="27283">
      <class name="swethapanchumarthy.Tests.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:swethapanchumarthy.Tests.SubmitOrderTest@7749bf93]" started-at="2023-02-13T10:01:36 IST" name="launchApplication" finished-at="2023-02-13T10:01:42 IST" duration-ms="6190" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:swethapanchumarthy.Tests.SubmitOrderTest@7749bf93]" started-at="2023-02-13T10:01:42 IST" name="submitOrder" data-provider="getData" finished-at="2023-02-13T10:01:48 IST" duration-ms="5695" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Practice@3239, product=ZARA COAT 3, email=pswetha308@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:swethapanchumarthy.Tests.SubmitOrderTest@7749bf93]" started-at="2023-02-13T10:01:48 IST" name="tearDown" finished-at="2023-02-13T10:01:49 IST" duration-ms="732" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:swethapanchumarthy.Tests.SubmitOrderTest@7749bf93]" started-at="2023-02-13T10:01:49 IST" name="launchApplication" finished-at="2023-02-13T10:01:53 IST" duration-ms="4275" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:swethapanchumarthy.Tests.SubmitOrderTest@7749bf93]" started-at="2023-02-13T10:01:53 IST" name="submitOrder" data-provider="getData" finished-at="2023-02-13T10:01:58 IST" duration-ms="4976" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Practice@3239, product=ADIDAS ORIGINAL, email=trainee@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:swethapanchumarthy.Tests.SubmitOrderTest@7749bf93]" started-at="2023-02-13T10:01:58 IST" name="tearDown" finished-at="2023-02-13T10:01:58 IST" duration-ms="347" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:swethapanchumarthy.Tests.SubmitOrderTest@7749bf93]" started-at="2023-02-13T10:01:58 IST" name="launchApplication" finished-at="2023-02-13T10:02:02 IST" duration-ms="3547" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="OrderHistoryTest()[pri:0, instance:swethapanchumarthy.Tests.SubmitOrderTest@7749bf93]" started-at="2023-02-13T10:02:02 IST" name="OrderHistoryTest" finished-at="2023-02-13T10:02:03 IST" depends-on-methods="swethapanchumarthy.Tests.SubmitOrderTest.submitOrder" duration-ms="939" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:swethapanchumarthy.Tests.SubmitOrderTest@7749bf93]" started-at="2023-02-13T10:02:03 IST" name="tearDown" finished-at="2023-02-13T10:02:03 IST" duration-ms="218" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- swethapanchumarthy.Tests.SubmitOrderTest -->
    </test> <!-- Submit Order Test -->
    <test started-at="2023-02-13T10:01:36 IST" name="Error Validations Test" finished-at="2023-02-13T10:02:04 IST" duration-ms="28384">
      <class name="swethapanchumarthy.Tests.ErrorValidations">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:swethapanchumarthy.Tests.ErrorValidations@6fb365ed]" started-at="2023-02-13T10:01:36 IST" name="launchApplication" finished-at="2023-02-13T10:01:41 IST" duration-ms="4889" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="loginerrorValidation()[pri:0, instance:swethapanchumarthy.Tests.ErrorValidations@6fb365ed]" started-at="2023-02-13T10:01:41 IST" name="loginerrorValidation" finished-at="2023-02-13T10:01:42 IST" duration-ms="743" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email password.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at swethapanchumarthy.Tests.ErrorValidations.loginerrorValidation(ErrorValidations.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginerrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:swethapanchumarthy.Tests.ErrorValidations@6fb365ed]" started-at="2023-02-13T10:01:42 IST" name="tearDown" finished-at="2023-02-13T10:01:42 IST" duration-ms="298" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:swethapanchumarthy.Tests.ErrorValidations@6fb365ed]" started-at="2023-02-13T10:01:42 IST" name="launchApplication" finished-at="2023-02-13T10:01:46 IST" duration-ms="3855" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginerrorValidation()[pri:0, instance:swethapanchumarthy.Tests.ErrorValidations@6fb365ed]" started-at="2023-02-13T10:01:46 IST" name="loginerrorValidation" finished-at="2023-02-13T10:01:46 IST" duration-ms="732" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email password.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at swethapanchumarthy.Tests.ErrorValidations.loginerrorValidation(ErrorValidations.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginerrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:swethapanchumarthy.Tests.ErrorValidations@6fb365ed]" started-at="2023-02-13T10:01:47 IST" name="tearDown" finished-at="2023-02-13T10:01:47 IST" duration-ms="225" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:swethapanchumarthy.Tests.ErrorValidations@6fb365ed]" started-at="2023-02-13T10:01:47 IST" name="launchApplication" finished-at="2023-02-13T10:01:52 IST" duration-ms="4191" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="producterrorValidation()[pri:0, instance:swethapanchumarthy.Tests.ErrorValidations@6fb365ed]" started-at="2023-02-13T10:01:52 IST" name="producterrorValidation" finished-at="2023-02-13T10:02:04 IST" duration-ms="12339" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- producterrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:swethapanchumarthy.Tests.ErrorValidations@6fb365ed]" started-at="2023-02-13T10:02:04 IST" name="tearDown" finished-at="2023-02-13T10:02:04 IST" duration-ms="259" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- swethapanchumarthy.Tests.ErrorValidations -->
    </test> <!-- Error Validations Test -->
  </suite> <!-- Suite -->
</testng-results>
